export const ERROR_MESSAGE = "ERROR_MESSAGE";
export const GET_DETAILS = "GET_DETAILS";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_PAGINADO = "GET_PRODUCTS_PAGINADO";
export const POST_PRODUCT = "POST_PRODUCT";
export const PUT_PRODUCT = "PUT_PRODUCT";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
export const RESET_PRODUCT_DETAIL = "RESET_PRODUCT_DETAIL";
export const GET_BRANDS_PRODUCTS = "GET_BRANDS_PRODUCTS";
export const GET_CATEGORIES_PRODUCTS = "GET_CATEGORIES_PRODUCTS";
export const GET_PRODUCTS_FOR_ADMIN = "GET_PRODUCTS_FOR_ADMIN";
export const GET_PRODUCTS_BY_NAME = "GET_PRODUCTS_BY_NAME";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORY_BY_ID = "GET_CATEGORY_BY_ID";
export const PUT_CATEGORY = "PUT_CATEGORY";
export const POST_CATEGORY = "POST_CATEGORY";
export const RESET_CATEGORY_DETAIL = "RESET_CATEGORY_DETAIL";
export const GET_CATEGORIES_FOR_ADMIN = "GET_CATEGORIES_FOR_ADMIN";
export const GET_CATEGORIES_BY_NAME = "GET_CATEGORIES_BY_NAME";

export const GET_BRANDS = "GET_BRANDS";
export const GET_BRAND_BY_ID = "GET_BRAND_BY_ID";
export const PUT_BRAND = "PUT_BRAND";
export const POST_BRAND = "POST_BRAND";
export const RESET_BRAND_DETAIL = "RESET_BRAND_DETAIL";
export const GET_BRANDS_FOR_ADMIN = "GET_BRANDS_FOR_ADMIN";
export const GET_BRANDS_BY_NAME = "GET_BRANDS_BY_NAME";

export const SET_USER_DATA = "SET_USER_DATA";
export const SET_USER_ERROR = "SET_USER_ERROR";
export const GET_PRODUCTS_CART = "GET_PRODUCTS_CART";
export const CLEAR_CART = "CLEAR_CART";
export const GET_REVIEWS = "GET_REVIEWS";
export const POST_REVIEWS = "POST_REVIEWS";
export const PUT_REVIEWS = "PUT_REVIEWS";
export const DELETE_REVIEW = "DELETE_REVIEW";
export const FILTER_BY_STATUS = "FILTER_BY_STATUS";

export const POST_CLOUDINARY_IMAGE = "POST_CLOUDINARY_IMAGE";

export const EDIT_USER_FRONT = "EDIT_USER_FRONT";
export const GET_ONE_USER = "GET_ONE_USER";
export const GET_USER_TICKETS = "GET_USER_TICKETS";
export const GET_ONE_TICKET = "GET_ONE_TICKET";
export const GET_WISHLIST = "GET_WISHLIST";
export const GET_DELIVERY= 'GET_DELIVERY';

export const GET_POLICY = "GET_POLICY";
export const GET_TYPE = "GET_TYPE";
export const GET_ONE_POLICY = "GET_ONE_POLICY";
export const POST_POLICY = "PUT_POLICY";
export const DELETE_POLICY = "DELETE_POLICY";
export const FILTER_BY_CATEGORY_POLICY="FILTER_BY_CATEGORY_POLICY";
export const GET_DELIVERIES = "GET_DELIVERIES";
export const PUT_DELIVERY = "PUT_DELIVERY";
