export const ERROR_MESSAGE = 'ERROR_MESSAGE';
export const GET_PRODUCTS_PAGINADO = 'GET_PRODUCTS_PAGINADO';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_DETAILS = 'GET_DETAILS';
export const GET_BRANDS_PRODUCTS ='GET_BRANDS_PRODUCTS';
export const GET_CATEGORIES_PRODUCTS= 'GET_CATEGORIES_PRODUCTS';
export const GET_BRANDS= 'GET_BRANDS';
export const GET_CATEGORIES= 'GET_CATEGORIES';



